services:
  - type: web
    name: http-backend
    env: node
    region: oregon
    buildCommand: pnpm install --no-frozen-lockfile && pnpm run build --filter=http-backend
    startCommand: cd apps/http-backend && pnpm run migrate:deploy && pnpm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
    healthCheckPath: /health

